#!/bin/bash

set -e
[ "$DEBUG" == "true" ] && env && set -x

export DAEMON=cat

USER=gatling

stop() {
  echo "Received SIGINT or SIGTERM."
  echo "Shutting down $DAEMON."
  # Get PID
  pid=$(cat "$ROOT_PATH/var/run/$DAEMON/$DAEMON.pid")
  # Signal the daemon
  kill -SIGTERM "$pid"
  # Wait for exit
  wait "$pid"
  # All done
  echo "Exiting"
}

echo "Running command \"$*\"."

if [ "$(basename "$1")" == "$DAEMON" ]; then
  trap stop SIGINT SIGTERM
  "$@" &
  pid="$!"
  mkdir -p "$ROOT_PATH/var/run/$DAEMON" && \
    echo "$pid" > "$ROOT_PATH/var/run/$DAEMON/$DAEMON.pid"
  wait "$pid" && exit $?
else
  exec "$@"
fi

