#!/bin/bash

set -e
[ "$DEBUG" == "true" ] && env && set -x

export DAEMON=cat

USER=frontline
HOME=$ROOT_PATH/home/probe

# hello blah
# Create a frontline user with current uid if needed
if ! whoami &> /dev/null; then
  if [ -w /etc/passwd ]; then
    echo "$USER:x:$(id -u):0::$HOME:/bin/bash" >> /etc/passwd
  fi
fi

#When sidecar is injected, wait for sidecar to come up
if [[ "$MESH_ENABLED" == "true" ]]; then
until (echo >/dev/tcp/localhost/$MESH_SIDECAR_PORT) &>/dev/null ; do echo Waiting for Sidecar; sleep 3 ; done ; echo Sidecar available;
fi

./bin/bootstrap $@
